CREATE TABLE `USERS` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_PASSWORD` varchar(20) NOT NULL,
  `FIRST_NAME` varchar(20) NOT NULL,
  `LAST_NAME` varchar(20) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `PHONE` varchar(10) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `EMAIL` (`EMAIL`)
);


CREATE TABLE `ADDRESSES` (
  `USER_ID` int NOT NULL,
  `CITY` varchar(20) NOT NULL,
  `STATE` varchar(20) NOT NULL,
  `COUNTRY` varchar(20) NOT NULL,
  `PIN_CODE` int NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `addresses_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`)
);

CREATE TABLE `CART` (
  `CART_ID` int NOT NULL,
  `USER_ID` int NOT NULL,
  `TOTAL_AMOUNT` float NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ADDRESS` varchar(250) DEFAULT NULL,
  `ORDER_STATUS` enum('PENDING','CANCELLED','SHIPPED','COMPLETED','REFUNDED') DEFAULT NULL,
  PRIMARY KEY (`CART_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `cart_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`)
);

CREATE TABLE `CART_ITEM` (
  `QUANTITY` int NOT NULL,
  `CART_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `PRICE` float NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `PRODUCT_ID` (`PRODUCT_ID`),
  KEY `CART_ID` (`CART_ID`),
  CONSTRAINT `cart_item_ibfk_1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`),
  CONSTRAINT `cart_item_ibfk_2` FOREIGN KEY (`CART_ID`) REFERENCES `CART` (`CART_ID`)
);

CREATE TABLE `PAYMENT` (
  `USER_ID` int NOT NULL,
  `PAYMENT_ID` int NOT NULL,
  `PAYMENT_DATE` date NOT NULL,
  `PAYMENT_TYPE` varchar(10) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PAYMENT_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `payment_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`)
);

CREATE TABLE `PRODUCTS` (
  `PRODUCT_ID` int NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` varchar(100) NOT NULL,
  `PRICE` float NOT NULL,
  `QUANTITY` int NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRODUCT_ID`)
);

